### ISSUE TITLE
nxus:storage:error Error: `migrate: "alter"` strategy is not supported in production, please change to `migrate: "safe"`.

### ISSUE THREAD

**Issue by davidkellerman** [nxus/storage#24]
npm run prod on timetracker demo app produces this error:
```
  nxus:storage:error Error: `migrate: "alter"` strategy is not supported in production, please change to `migrate: "safe"`.
___Stack trace #1___
Error: `migrate: "alter"` strategy is not supported in production, please change to `migrate: "safe"`.
    at module.exports [as migrateAlter] (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/lib/waterline/adapter/sync/strategies/alter.js:21:15)
    at child.Query.sync (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/lib/waterline/query/index.js:67:37)
    at /Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/lib/waterline.js:280:16
    at /Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:181:20
    at iterate (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:214:22)
    at bootstrap (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/lib/waterline.js:278:9)
    at /Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/lib/waterline.js:209:10
    at /Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:550:17
    at /Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:544:17
    at _arrayEach (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/Users/david_kellerman/Documents/Seabourne/timetracker/node_modules/waterline/node_modules/async/lib/async.js:543:13)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5) +2s
```

**Comment by davidkellerman** [comment]
Need to set nxus_storage__defaults__migrate environment variable
```
nxus_storage__defaults__migrate=safe npm run prod
```
